Update recipe dependencies
conda-forge/uvicorn-feedstock pull request #74
Opened 2021-08-20 13:47 UTC by abraha2d

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

We encountered an a failed deploy of a product yesterday. Upon investigation, we found that the uvicorn conda-forge package was not correctly specifying its dependency on asgiref (the recipe says `asgiref >=3.3.4`, but uvicorn v0.15.0 actually requires `asgiref >=3.4.0`).

This PR re-generates the recipe using [grayskull](https://github.com/conda-incubator/grayskull). Please let me know if the new recipe is missing anything that should really be added back from the previous version.

2021-08-20 13:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-08-20 13:47 UTC, abraha2d commented
@conda-forge-admin, please rerender

2021-08-21 05:28 UTC, xhochy requested changes
Please only change the single dependency, you are removing all the cross-compiling and the custom (longer description).

2021-08-22 18:06 UTC, abraha2d commented
@conda-forge-admin, please rerender

2021-08-22 18:09 UTC, abraha2d commented
Hi, sorry about that, I've rolled back all the other changes. Should be good to go now.

2021-08-29 20:03 UTC, merged